sudo: required
services:
  - docker

before_install:
  - docker build -t leegengzhao/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leegengzhao/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "bucketselasticbeanstalk-us-west-1-186953810997"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
